### ISSUE TITLE
Nuclear Power Plants need Waste Output

### ISSUE THREAD

**Issue by Bingmano** [satisfactory-accounting/satisfactory-accounting#20]
Nuke plants should have a waste generation output considered for calculations. this would be helpful if you're trying to balance waste conversion to plutonium rods or trying to determine how much waste will be produced per min to calculate a storage option.

in its current form, plants would need a fuel type input in order to properly calculate (uranium vs plutonium).

**Comment by zstewar1** [comment]
Interesting. Nuke plants do have an option to select the input fuel, and the database does have an entry in each fuel type for "byproducts". It appears that when I wrote the calculations for the balance of generator inputs/outputs I just forgot to calculate the byproducts. This is a pretty trivial fix and I should be able to get to it this weekend.

**Comment by Bingmano** [comment]
excellent! Love the tool, it's extremely helpful.
