### ISSUE TITLE
Water Extractor does not show water production

### ISSUE THREAD

**Issue by tasonosenshi** [satisfactory-accounting/satisfactory-accounting#23]
While planning a power plant, the water extractor shows "0" for the water output.  It should show 120 at 100% clock speed.

![image](https://github.com/user-attachments/assets/31532d8e-2efb-47c9-a365-a9e2570d789b)

**Comment by zstewar1** [comment]
Should be fixed by 6d57786fcfd103e72672be3d3aab54ae75a2aa31. You can update the database to the version with the fix from the version selector in the UI.

Thanks for reporting.
