### ISSUE TITLE
Page error, full grey screen, no save

### ISSUE THREAD

**Issue by JuAnEs33-33** [satisfactory-accounting/satisfactory-accounting#26]
Hello, i have an issue with the tool since last updates (it worked perfectly before), when i open the tool on web i do my factories like usual but if i quit the page and i reopen the page my factories aren't saved and i have a full grey screen.. i don't understand why i have this issue now. If anyone could help please. Thank you

**Comment by zstewar1** [comment]
Hi, sorry to hear that!

Please first make sure that you've refreshed the page (Ctrl+R on most browsers), not just closed and reopened it.

If that doesn't fix it, can you please tell me:

1. What browser are you using
2. Attach a screenshot showing what you actually see.
3. Open the browser developer tools. This is often `F12` or `Ctrl+Shift+I` or just find developer tools in the menu. Check the Console there for any error messages and copy them for me.

**Comment by JuAnEs33-33** [comment]
Hello, thanks for your answer. Ctrl+R have no effect. I'm using google chrome but i have the same issue on each browsers i'm using. i attached what i see on the screen [
![Desktop Screenshot 2024 09 22 - 10 23 43 11](https://github.com/user-attachments/assets/5c77d63d-bd08-4f81-a71c-f9e4a6637b9f)
](url) 
And i attached the errors in the developer tools. 
![Desktop Screenshot 2024 09 22 - 10 25 39 52](https://github.com/user-attachments/assets/0bdb948f-d870-47f6-8e7b-5b86fb08820d)

**Comment by zstewar1** [comment]
Looks like https://github.com/rustwasm/wasm-pack/issues/1389

I will try updating dependencies when I get a chance which should fix it. Hopefully can get to this on monday!

**Comment by zstewar1** [comment]
It appears to be caused by how JS passes text to WASM:

https://github.com/rustwasm/wasm-bindgen/issues/3801

I was able to reproduce your issue by using non-ascii text in the name of a Group, so I can now test fixes on my end.

**Comment by JuAnEs33-33** [comment]
Thank you very much :) i hope you will fix because i really like your tool

**Comment by zstewar1** [comment]
The code change to fix this is done, though I won't be able to deploy it until a bit later; will let you know when it is live.

**Comment by zstewar1** [comment]
Should work again now!

**Comment by JuAnEs33-33** [comment]
Hello, it looks like the fix worked for me i don't have the grey screen error ! thank you so much for your help and your work, your tool is insane !
