### ISSUE TITLE
Power generators Overclock is givin wrong values

### ISSUE THREAD

**Issue by ThisisDemian** [satisfactory-accounting/satisfactory-accounting#31]
When tryin to overclock power generators like the coal generator, once you change the value it doesn't change according to the in game values.

Ex.:
Coal generator at 100%
in game -> -15 coal, -45 water, +75 MW
SA -> -15 coal, -45 water,+75 MW

Coal generator at 200%
in game -> -30 coal, -90 water, +150 MW
SA -> -23.13 coal, -69.4 water, +115.67 MW

**Comment by zstewar1** [comment]
Ah, right at some point they changed it so overclocked generators scale linearly (while other machines still lose efficiency when overclocked). I'll see about fixing that this week.
